### ISSUE TITLE
Not working with bitmetv.org

### ISSUE THREAD

**Issue by goodyear77** [Zymest/autodl-curl-sonarr#1]
Hi, 

would it be possible to update the script to make use of the cookie requirement that bitmetv.org has for downloading torrents?

Thanks!

**Comment by goodyear77** [comment]
As per usual, as soon as you ask the question you figure out the answer... For anyone else wanting to do this:

Update the autodl-curl-sonarr.sh script to include the bitmetv cookie by adding "--cookie "uid=YOUR_COOKIE_UID;pass=YOUR_COOKIE_PASS" to the curl command

The line should look like this:

/usr/bin/curl -v --cookie "uid=YOUR_UID;pass=YOUR_PASS" -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Api-Key: $apiKey" -X POST -d '{"title":"'"$title"'","downloadUrl":"'"$downloadUrl"'","downloadProtocol":"torrent","publishDate":"'"$date"'"}' http://localhost:8989/api/release/push

Set up your autodl.cfg (located here: ~/.autodl/autodl.cfg) to include something like this, either in the global [options] header or for specific [filter]s as you see fit (I setup and use a "Match All" filter).

Add "?uid=YOUR_UID&passkey=YOUR_PASSKEY" (without quotes) after "$(TorrentUrl)" to append your login information:

Update the path to the script and YOUR_UID, YOUR_PASSKEY YOUR_SONARR_API_KEY to the values for your system:

upload-type = exec
upload-command = /path/to/autodl-curl-sonarr.sh
upload-args = "$(TorrentName)" "$(TorrentUrl)?uid=YOUR_UID&passkey=YOUR_PASSKEY" YOUR_SONARR_API_KEY

You can set up autodl-irssi filters to simply match everything and let Sonarr decide what it should download based upon your Sonarr configuration.

**Comment by goodyear77** [comment]
Seems I spoke a bit too soon... It works from the command line, when I run the shell script and provide the arguments myself, but it doesn't work when invoked by the filter. 

Is it perhaps a permission issue, is the filter running the script as a different user than the one I'm logged in as? When I check by running the command "ps aux" it looks like rtorrent as well as irssi is running as the local user.

I've done a chmod 777 on the shell script and placed it in the local user's home directory, but I can only test once a day for the filter to pick it up which makes it take a bit long to test...

**Comment by Zymest** [comment]
Closing per this: https://forums.sonarr.tv/t/solved-use-autodl-curl-sonarr-with-bitmetv/11732/7
