### ISSUE TITLE
Radarr Support?

### ISSUE THREAD

**Issue by Metigoth** [Zymest/autodl-curl-sonarr#2]
Will it work with Radarr? If not can you modify it to work with Radarr?

**Comment by shrouski** [comment]
I don't see why it wouldn't work. If it doesn't you'd need to request them to update their API to support it, as I checked checked their github and it's the same as Sonarr.

https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Api/Indexers/ReleasePushModule.cs
