### ISSUE TITLE
Date timezone format incompatible with Sonarr

### ISSUE THREAD

**Issue by Taloth** [Zymest/autodl-curl-sonarr#3]
~~`date=$(date -u +"%Y-%m-%d %H:%M:%SZ")`
should be
`date=$(date -u +"%Y-%m-%d %H:%M:%S %Z")`
so it outputs " UTC" instead of "Z" as suffix.~~

**Comment by talentedmrripley** [comment]
After fixing the missing %, Sonarr won't process the input anymore.  Gives the following error:

`Nancy.ModelBinding.ModelBindingException: Unable to bind to type: NzbDrone.Api.Indexers.ReleaseResource ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: 2017-07-12 22:17:48 UTC is not a valid value for DateTime. ---> System.FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 20.`

Tried it with and without a space between the %S and %Z.  Same error with the only the index in the error message changing.  For now I've removed the -u and the %Z.

**Comment by Taloth** [comment]
Yes, I was far too quick to suggest the change. I added a couple of testcases to Sonarr to see how it reacts, both "Z" and " GMT" suffixes work, but "UTC" does not.

And I couldn't explain the 6h offset we saw, till I compared some code on how ReleasePush worked vs the RSS parser and I found a discrepancy.
So... yeah.. the problem is on our end.

**Comment by talentedmrripley** [comment]
The script should still be updated to add the missing % so that it outputs UTC instead of the Z.

**Comment by Taloth** [comment]
No, coz it's supposed to be 'Z' or 'GMT'. UTC doesn't exist in .net. The problem wasn't that Sonarr couldn't parse it, it simply incorrectly calculated the age.
