### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NissimDE** [Zymest/autodl-curl-sonarr#4]
Hi, Ive tried to get this working on 2 different servers and Its not working. The filter seems to be finding everything from the TV categories, but nothing gets downloaded. Not sure what do do :( Any way that you could assist me?

**Comment by xnaas** [comment]
Are you getting this error too?

>Can't save/upload torrent: Torrent action 'exec' is disabled!

**Comment by SirSilent** [comment]
@muddro1 - my autodl is installed in my home dir (actually it always has been every time I've seen it, so surprised yours is root. Every install script I've used puts it in the home dir). My command is 

~/.autodl/autodl-curl-sonarr.sh

No issues. Worked for a couple of years.

**Comment by muddro1** [comment]
Ive done it where i just put it in /, in my /mnt/, in the scripts folder. No matter where it is, it does not seem to "find" it.

**Comment by muddro1** [comment]
Fixed it. path to bash and curl were off for freenas. need to be /usr/local/bin/bash and usr/local/bin/curl

**Comment by muddro1** [comment]
Having issue. Script is executing, or appears to, but it's not triggering the API of sonarr/radar. How can one trouble shoot this?
