### ISSUE TITLE
vars are not being passed into the curl command.

### ISSUE THREAD

**Issue by Rick7C2** [Zymest/autodl-curl-sonarr#5]
$title, $downloadUrl, $date Are not resolving to their set date in the curl command. $apiKey is just fine

This is the curl command this script executes...

curl -i -H Accept: application/json -H Content-Type: application/json -H X-Api-Key: 07422a02b3593855a4a1b5baffded9c8 -X POST -d '{title:"$title",downloadUrl:"$downloadUrl",downloadProtocol:torrent,publishDate:"$date"}' http://localhost/sonarr/api/release/push

This is how the script was called...

/home/sonarr/scripts/autodl-curl-sonarr.sh "Tosh.0.S09E28.720p.HDTV.x264-MiNDTHEGAP" "https://www.morethan.tv/torrents.php?action=download&id=0000000000&authkey=0000000000&torrent_pass=0000000000" "07422a02b3593855a4a1b5baffded9c8"

**Comment by Rick7C2** [comment]
nevermind figured it out

**Comment by arebokert** [comment]
@Rick7C2 Be so kind and inform us of how you solved the issue so others may use the information
