### ISSUE TITLE
Sonarr location

### ISSUE THREAD

**Issue by xpronic** [Zymest/autodl-curl-sonarr#6]
Does  sonarr have to be installed on the seedbox along with the script for it to work, or can I use sonarr locally and be good to go?

**Comment by Zymest** [comment]
You could set it up to work remotely.  You would need to have a way for the script to communicate with sonarr over the internet, and make sure that sonarr would listen.  I would set up a reverse proxy for sonarr and have the script send releases to the appropriate URL.
